import { describe, it, expect, vi, beforeEach } from 'vitest';
import { ProblemStatus } from '../mongoose/schemas/problems';

describe('ProblemStatus enum', () => {
  it('should have the correct values', () => {
    expect(ProblemStatus.Ready).toBe('ready');
    expect(ProblemStatus.Waiting).toBe('waiting');
    expect(ProblemStatus.Error).toBe('error');
  });
});

describe('statusReason field on problem schema', () => {
  it('should be included in the schema', async () => {
    // Dynamically import to avoid side effects
    const { problemSchema } = await import('../mongoose/schemas/problems');
    const paths = problemSchema.paths;
    expect(paths).toHaveProperty('statusReason');
  });

  it('should be optional (no required flag)', async () => {
    const { problemSchema } = await import('../mongoose/schemas/problems');
    const statusReasonPath = problemSchema.paths['statusReason'] as any;
    expect(statusReasonPath.isRequired).toBeFalsy();
  });
});

describe('testcase generation error handling', () => {
  it('should detect when no .in files are present in the tests directory', () => {
    const generatedFiles = ['mapping', 'subtasks.json', 'readme.txt'];
    const hasTestcases = generatedFiles.some((f) => f.endsWith('.in'));
    expect(hasTestcases).toBe(false);
  });

  it('should detect testcases when .in files are present', () => {
    const generatedFiles = ['mapping', '1-01.in', '1-01.out', '1-02.in', '1-02.out'];
    const hasTestcases = generatedFiles.some((f) => f.endsWith('.in'));
    expect(hasTestcases).toBe(true);
  });

  it('should format the error message for status update', () => {
    const genError = new Error('No testcases were generated by tps gen (no .in files found)');
    const statusReason = genError instanceof Error ? genError.message : String(genError);
    expect(statusReason).toBe('No testcases were generated by tps gen (no .in files found)');
  });

  it('should stringify non-Error objects for statusReason', () => {
    const genError = 'tps gen exited with non-zero status';
    const statusReason = genError instanceof Error ? genError.message : String(genError);
    expect(statusReason).toBe('tps gen exited with non-zero status');
  });

  it('should call findByIdAndUpdate with statusReason on error', async () => {
    const findByIdAndUpdate = vi.fn().mockResolvedValue(null);
    const genError = new Error('Tests directory not generated by tps gen');
    const problemId = 'mockedid123';

    await findByIdAndUpdate(problemId, {
      status: ProblemStatus.Error,
      statusReason: genError instanceof Error ? genError.message : String(genError),
    });

    expect(findByIdAndUpdate).toHaveBeenCalledWith(problemId, {
      status: ProblemStatus.Error,
      statusReason: 'Tests directory not generated by tps gen',
    });
  });

  it('should use $unset to clear statusReason on success', async () => {
    const findByIdAndUpdate = vi.fn().mockResolvedValue(null);
    const problemId = 'mockedid123';

    await findByIdAndUpdate(problemId, {
      $set: { status: ProblemStatus.Ready },
      $unset: { statusReason: 1 },
    });

    expect(findByIdAndUpdate).toHaveBeenCalledWith(problemId, {
      $set: { status: ProblemStatus.Ready },
      $unset: { statusReason: 1 },
    });
  });
});

describe('gen_summary first non-manual testcase selection', () => {
  it('should skip manual entries and return the first generatable testcase', () => {
    const genSummaryContent = [
      '# comment line',
      '1-manual-01 1 manual',
      '1-01 1 gen 42',
      '1-02 1 gen 43',
    ].join('\n');

    let firstTestcase: string | null = null;
    for (const line of genSummaryContent.split('\n')) {
      if (!line.trim() || line.trim().startsWith('#')) continue;
      const parts = line.trim().split(/\s+/);
      if (parts.length >= 3 && !parts.slice(2).join(' ').startsWith('manual')) {
        firstTestcase = parts[0];
        break;
      }
    }
    expect(firstTestcase).toBe('1-01');
  });

  it('should return null when all testcases are manual', () => {
    const genSummaryContent = [
      '1-01 1 manual',
      '1-02 1 manual',
    ].join('\n');

    let firstTestcase: string | null = null;
    for (const line of genSummaryContent.split('\n')) {
      if (!line.trim() || line.trim().startsWith('#')) continue;
      const parts = line.trim().split(/\s+/);
      if (parts.length >= 3 && !parts.slice(2).join(' ').startsWith('manual')) {
        firstTestcase = parts[0];
        break;
      }
    }
    expect(firstTestcase).toBeNull();
  });

  it('should return null for an empty gen_summary', () => {
    const genSummaryContent = '';

    let firstTestcase: string | null = null;
    for (const line of genSummaryContent.split('\n')) {
      if (!line.trim() || line.trim().startsWith('#')) continue;
      const parts = line.trim().split(/\s+/);
      if (parts.length >= 3 && !parts.slice(2).join(' ').startsWith('manual')) {
        firstTestcase = parts[0];
        break;
      }
    }
    expect(firstTestcase).toBeNull();
  });
});
