export const problems = [
  { id: 1, title: 'Binary Search', difficulty: 'Easy', submissions: 450, accuracy: '85%' },
  { id: 2, title: 'Two Sum', difficulty: 'Medium', submissions: 1200, accuracy: '67%' },
  { id: 3, title: 'Travelling Salesman', difficulty: 'Hard', submissions: 350, accuracy: '45%' },
  { id: 4, title: 'Merge Sort', difficulty: 'Easy', submissions: 550, accuracy: '90%' },
  { id: 5, title: 'Quick Sort', difficulty: 'Medium', submissions: 1100, accuracy: '78%' },
  { id: 6, title: 'Depth-First Search', difficulty: 'Medium', submissions: 900, accuracy: '72%' },
  { id: 7, title: 'Breadth-First Search', difficulty: 'Medium', submissions: 950, accuracy: '80%' },
  { id: 8, title: 'Dynamic Programming', difficulty: 'Hard', submissions: 600, accuracy: '60%' },
  { id: 9, title: 'Linked List Reversal', difficulty: 'Easy', submissions: 700, accuracy: '92%' },
  { id: 10, title: 'Knapsack Problem', difficulty: 'Hard', submissions: 400, accuracy: '55%' },
  { id: 11, title: 'Maximum Subarray Sum', difficulty: 'Easy', submissions: 600, accuracy: '88%' },
  { id: 12, title: 'Floyd-Warshall Algorithm', difficulty: 'Hard', submissions: 250, accuracy: '48%' },
  { id: 13, title: "Dijkstra's Algorithm", difficulty: 'Medium', submissions: 850, accuracy: '70%' },
  { id: 14, title: "Prim's Algorithm", difficulty: 'Medium', submissions: 780, accuracy: '77%' },
  { id: 15, title: 'Topological Sorting', difficulty: 'Hard', submissions: 300, accuracy: '52%' },
];
